name: devtailor_task_richardas
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/devtailor_logo.svg
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Thin.otf
          weight: 100
        - asset: assets/fonts/inter/Inter-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/inter/Inter-Light.otf
          weight: 300
        - asset: assets/fonts/inter/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/inter/Inter-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/inter/Inter-Black.otf
          weight: 900
